variable "azure_subscription_id" {}
variable "azure_client_id" {}
variable "azure_client_secret" {}
variable "azure_tenant_id" {}
variable "svc_vco_ipam_username" {}
variable "svc_vco_ipam_password" {}
variable "resource_group_name" {}
variable "location_code" {}
variable "project_name" {}
variable "location" {}
variable "environment" {}
variable "vnet_name" {}
variable "subnet_name" {}
variable "vnet_rg" {}
