@Library('arcus-pipeline-library@master') _

env.NAME = 'terraform-azurerm-sharedgallery'

// Azure vars
env.MODULE_TYPE = 'azure'

// Troubleshooting vars
//env.IMAGE_KEEP = 'true'
//env.KITCHEN_DESTROY = 'passing'
//env.KITCHEN_DESTROY = 'never'
//env.KITCHEN_LOG = 'debug'
env.TF_VERSION = '0.13.0'

terraformPipeline()