---
driver:
  name: terraform
  root_module_directory: test/integration/terraform/plan/ 
  command_timeout: 900
  color: true
  parallelism: 1
  variables:
    azure_client_id: "<%= ENV['AZURE_CLIENT_ID'] %>"
    azure_client_secret: "<%= ENV['AZURE_CLIENT_SECRET'] %>"
    azure_subscription_id: "<%= ENV['AZURE_SUBSCRIPTION_ID'] %>"
    azure_tenant_id: "<%= ENV['AZURE_TENANT_ID'] %>"

provisioner:
  name: terraform

platforms:
  - name: terraform 

verifier:
  name: terraform
  systems:
    - name: azure
      backend: azure
      reporter:
        - junit:inspec_output.xml

suites:
  - name: terraform
