---
driver:
  name: terraform
  root_module_directory: test/integration/terraform/plan/ 
  command_timeout: 600
  color: true
  variables:
    azure_client_id: "<%= ENV['AZURE_CLIENT_ID'] %>"
    azure_client_secret: "<%= ENV['AZURE_CLIENT_SECRET'] %>"
    azure_subscription_id: "<%= ENV['AZURE_SUBSCRIPTION_ID'] %>"
    azure_tenant_id: "<%= ENV['AZURE_TENANT_ID'] %>"
    svc_vco_ipam_username: "<%= ENV['SVC_VCO_IPAM_USERNAME'] %>"
    svc_vco_ipam_password: "<%= ENV['SVC_VCO_IPAM_PASSWORD'] %>"

provisioner:
  name: terraform

platforms:
  - name: terraform 

verifier:
  name: terraform
  systems:
    - name: azure
      backend: azure
      reporter:
        - junit:inspec_output.xml

suites:
  - name: terraform
